language: node_js

node_js:
  - "12"

before_script:
  # Notify Code Climate.
  - curl --location
      https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 >
      $HOME/bin/code-climate
  - chmod +x $HOME/bin/code-climate
  - code-climate before-build

notifications:
  email: false

git:
  depth: 1
  quiet: true
