steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "--build-arg", "BUILD_VERSION=$SHORT_SHA",
      "--tag", "gcr.io/doraboateng/web:$COMMIT_SHA",
      "--target", "prod",
      ".",
    ]
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "gcr.io/doraboateng/web:$COMMIT_SHA",
    ]
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run", "deploy", "web",
      "--allow-unauthenticated",
      "--image", "gcr.io/doraboateng/web:$COMMIT_SHA",
      "--platform", "managed",
      "--region", "us-east1",
    ]

images:
  - gcr.io/doraboateng/web
