version: "3.4"
services:

  web:
    image: doraboateng/web:dev
    build:
      context: "."
      target: dev
    command: yarn dev --port 3300
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://api:8800
      BUILD_VERSION: dev
    ports:
      - "3300:3300"
    volumes:
      - .:/boateng-web:cached

  api:
    image: doraboateng/api:latest
    depends_on:
      - zero
      - alpha
    environment:
      BOATENG_API_PORT: 8800 # Backwards compatibility
      PORT: 8800
    ports:
      - "8800:8800"

  zero:
    image: doraboateng/graph:latest
    command: >-
      dgraph zero
        --bindall
        --block_rate 10
        --expose_trace
        --logtostderr
        --my=zero:5080
        --profile_mode block
        -v=2
    volumes:
      - dgraph_vol:/dgraph:delegated
    working_dir: /data/zero

  alpha:
    image: doraboateng/graph:latest
    command: >-
      dgraph alpha
        --block_rate 10
        --expose_trace
        --logtostderr
        --lru_mb=1024
        --my=alpha:7080
        --profile_mode block
        --trace 1.0
        -v=2
        --zero=zero:5080
    depends_on:
      - zero
    ports:
      - "8080:8080"
    volumes:
      - dgraph_vol:/dgraph:delegated
    working_dir: /data/alpha

volumes:
  dgraph_vol:
